services:
  collective-app:
    container_name: collective-con
    image: collective-img  # Custom image name
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - collective-data:/app/data  # Custom named persistent storage for app data
      - collective-env:/app/.venv  # Custom named persistent Poetry virtual environment
    environment:
      - ENV_VARIABLE=collective-var
    ports:
      - "8000:8000"
    working_dir: /app
    command: ["/bin/bash", "-c", "while true; do sleep 30; done"]  # Keeps container running
    networks:
      - collective-net

volumes:
  collective-data:
    name: collective-data
  collective-env:
    name: collective-env

networks:
  collective-net:
    name: collective-net
    driver: bridge
